### ISSUE TITLE
mac 10.9 安装时错误 打不开以下磁盘镜像

### ISSUE THREAD

**Issue by outman** [hjue/php-manual-mac#1]
![qq20140217-1](https://f.cloud.github.com/assets/532893/2182352/f2d4728c-9785-11e3-8514-23d51b5be8e8.png)

mac 10.9 安装时错误

**Comment by hjue** [comment]
感谢你反馈的问题。

错误原因我已经找到，是由于github的文件服务器文件错误造成的。你下载的文件大小应该是0字节。

从这个地址重新[下载](https://raw2.github.com/hjue/php-manual-mac/master/release/PHPHandBook.dmg)就可以安装了 https://raw2.github.com/hjue/php-manual-mac/master/release/PHPHandBook.dmg。

PS：从这个地址下载的字节数就是零，https://raw2.github.com/hjue/php-manual-mac/master/release/PHPHandBook.dmg 。
